const SSH_MSG_DISCONNECT       = 1
const SSH_MSG_IGNORE           = 2
const SSH_MSG_UNIMPLEMENTED    = 3
const SSH_MSG_DEBUG            = 4
const SSH_MSG_SERVICE_REQUEST  = 5
const SSH_MSG_SERVICE_ACCEPT   = 6
const SSH_MSG_KEXINIT          = 20
const SSH_MSG_NEWKEYS          = 21
const SSH_MSG_KEXDH_INIT       = 30
const SSH_MSG_KEXDH_REPLY      = 31
const SSH_MSG_USERAUTH_REQUEST = 50
const SSH_MSG_USERAUTH_FAILURE = 51
const SSH_MSG_USERAUTH_SUCCESS = 52
const SSH_MSG_USERAUTH_BANNER  = 53

# Messages for Authentication method publickey
const SSH_MSG_USERAUTH_PK_OK   = 60

# Messages for Authentication method keyboard-interactive
const SSH_MSG_USERAUTH_INFO_REQUEST     =  60
const SSH_MSG_USERAUTH_INFO_RESPONSE    =  61

# Messages for ssh-connection
const SSH_MSG_GLOBAL_REQUEST            =  80
const SSH_MSG_REQUEST_SUCCESS           =  81
const SSH_MSG_REQUEST_FAILURE           =  82
const SSH_MSG_CHANNEL_OPEN              =  90
const SSH_MSG_CHANNEL_OPEN_CONFIRMATION =  91
const SSH_MSG_CHANNEL_OPEN_FAILURE      =  92
const SSH_MSG_CHANNEL_WINDOW_ADJUST     =  93
const SSH_MSG_CHANNEL_DATA              =  94
const SSH_MSG_CHANNEL_EXTENDED_DATA     =  95
const SSH_MSG_CHANNEL_EOF               =  96
const SSH_MSG_CHANNEL_CLOSE             =  97
const SSH_MSG_CHANNEL_REQUEST           =  98
const SSH_MSG_CHANNEL_SUCCESS           =  99
const SSH_MSG_CHANNEL_FAILURE           = 100

const SSH_OPEN_ADMINISTRATIVELY_PROHIBITED = 1
const SSH_OPEN_CONNECT_FAILED              = 2
const SSH_OPEN_UNKNOWN_CHANNEL_TYPE        = 3
const SSH_OPEN_RESOURCE_SHORTAGE           = 4


const SSH_DISCONNECT_HOST_NOT_ALLOWED_TO_CONNECT    =  1
const SSH_DISCONNECT_PROTOCOL_ERROR                 =  2
const SSH_DISCONNECT_KEY_EXCHANGE_FAILED            =  3
const SSH_DISCONNECT_RESERVED                       =  4
const SSH_DISCONNECT_MAC_ERROR                      =  5
const SSH_DISCONNECT_COMPRESSION_ERROR              =  6
const SSH_DISCONNECT_SERVICE_NOT_AVAILABLE          =  7
const SSH_DISCONNECT_PROTOCOL_VERSION_NOT_SUPPORTED =  8
const SSH_DISCONNECT_HOST_KEY_NOT_VERIFIABLE        =  9
const SSH_DISCONNECT_CONNECTION_LOST                = 10
const SSH_DISCONNECT_BY_APPLICATION                 = 11
const SSH_DISCONNECT_TOO_MANY_CONNECTIONS           = 12
const SSH_DISCONNECT_AUTH_CANCELLED_BY_USER         = 13
const SSH_DISCONNECT_NO_MORE_AUTH_METHODS_AVAILABLE = 14
const SSH_DISCONNECT_ILLEGAL_USER_NAME              = 15
